### ISSUE TITLE
Getting these errors when unmounting animated div

### ISSUE THREAD

**Issue by FrancescoCoding** [mijim/react-mount-animation#2]
![image](https://user-images.githubusercontent.com/64712227/134599089-d618fd04-7df2-4557-a403-e28cad12815f.png)

Seems like the fix should be changing something like:

`animation: all 2s`

to
```
animationName: all
animationDuration: 2s
```

These are the animations I'm using:

`      mountAnim={` 
            0% {transform: translateX(-100%)}
            100% {transform: translateX(0)}
        `}
      unmountAnim={` 
            0% {transform: translateX(0)}
            100% {transform: translateX(-100%)}
        `}`

**Comment by mijim** [comment]
Thank you for the advice! I'm going to fix it with the solution you prupose.
